// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJMo-YQCIK8E3EnjSZMw1qmDI3_edRfG8',
    appId: '1:355526621008:web:c3220529341087acfede55',
    messagingSenderId: '355526621008',
    projectId: 'weatherapp-c78ab',
    authDomain: 'weatherapp-c78ab.firebaseapp.com',
    storageBucket: 'weatherapp-c78ab.appspot.com',
    measurementId: 'G-MK6909QHSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1iNcZQtoBjCVcltHxjeI3Mu_mTarq-dc',
    appId: '1:355526621008:android:a2797c971771fd95fede55',
    messagingSenderId: '355526621008',
    projectId: 'weatherapp-c78ab',
    storageBucket: 'weatherapp-c78ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4b7izlaTL4nLeO36i2Xl_fF7Tq25-xKo',
    appId: '1:355526621008:ios:a15fd9a5b9451fcefede55',
    messagingSenderId: '355526621008',
    projectId: 'weatherapp-c78ab',
    storageBucket: 'weatherapp-c78ab.appspot.com',
    iosClientId: '355526621008-1i2v6f5o1dlkvs1otlbhv52cq9006k07.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherStation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4b7izlaTL4nLeO36i2Xl_fF7Tq25-xKo',
    appId: '1:355526621008:ios:a15fd9a5b9451fcefede55',
    messagingSenderId: '355526621008',
    projectId: 'weatherapp-c78ab',
    storageBucket: 'weatherapp-c78ab.appspot.com',
    iosClientId: '355526621008-1i2v6f5o1dlkvs1otlbhv52cq9006k07.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherStation',
  );
}
